### ISSUE TITLE
Exception on 'friday broadcast'

### ISSUE THREAD

**Issue by slux83** [slux83/friday-bot#11]
```
2018-09-06 11:30:20.442  WARN 18008 --- [https-jsse-nio-8080-exec-6] d.s.l.f.c.admin.AdminBroadcastCommand    : Cannot push message to group. Reason: java.util.concurrent.ExecutionException: com.linecorp.bot.client.exception.BadRequestException: Failed to send messages, ErrorResponse(message=Failed to send messages, details=[])
```

This needs to be investigated

**Comment by slux83** [comment]
Can't do much, added few traces to verify it in the future.

**Comment by slux83** [comment]
Fixed

**Comment by slux83** [comment]
Still seeing this

```
2018-10-10 15:51:31.877  WARN 26424 --- [https-jsse-nio-8080-exec-8] d.slux.line.friday.FridayBotApplication  : Cannot push message to group. Reason: java.util.concurrent.ExecutionException: com.linecorp.bot.client.exception.BadRequestException: Failed to send messages : ErrorResponse(requestId=870f535a-bf95-4101-9d96-7849ec653995, message=Failed to send messages, details=[])

java.util.concurrent.ExecutionException: com.linecorp.bot.client.exception.BadRequestException: Failed to send messages : ErrorResponse(requestId=870f535a-bf95-4101-9d96-7849ec653995, message=Failed to send messages, details=[])
        at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357) ~[na:1.8.0_181]
        at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895) ~[na:1.8.0_181]
        at de.slux.line.friday.FridayBotApplication.pushMultiMessages(FridayBotApplication.java:505) [friday-bot-0.0.4.jar:na]
        at de.slux.line.friday.command.admin.AdminBroadcastCommand.execute(AdminBroadcastCommand.java:88) [friday-bot-0.0.4.jar:na]
        at de.slux.line.friday.FridayBotApplication.handleUserSource(FridayBotApplication.java:269) [friday-bot-0.0.4.jar:na]
        at de.slux.line.friday.FridayBotApplication.handleTextMessageEvent(FridayBotApplication.java:227) [friday-bot-0.0.4.jar:na]
        at sun.reflect.GeneratedMethodAccessor33.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_181]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_181]
        at com.linecorp.bot.spring.boot.support.LineMessageHandlerSupport.dispatchInternal(LineMessageHandlerSupport.java:195) [line-bot-spring-boot-2.0.0.jar:2.0.0]
        at com.linecorp.bot.spring.boot.support.LineMessageHandlerSupport.dispatch(LineMessageHandlerSupport.java:180) [line-bot-spring-boot-2.0.0.jar:2.0.0]
        at java.util.ArrayList.forEach(ArrayList.java:1257) ~[na:1.8.0_181]
        at com.linecorp.bot.spring.boot.support.LineMessageHandlerSupport.callback(LineMessageHandlerSupport.java:174) [line-bot-spring-boot-2.0.0.jar:2.0.0]

```
