### ISSUE TITLE
Fix crash

### ISSUE THREAD

**Issue by slux83** [slux83/friday-bot#33]
```
java.lang.NullPointerException: null
        at java.util.TreeMap.getEntry(TreeMap.java:347) ~[na:1.8.0_191]
        at java.util.TreeMap.containsKey(TreeMap.java:232) ~[na:1.8.0_191]
        at de.slux.line.friday.command.war.WarDiversityCommand.execute(WarDiversityCommand.java:173) ~[friday-bot-0.1.1.jar:na]
        at de.slux.line.friday.FridayBotApplication.handleGroupSource(FridayBotApplication.java:310) [friday-bot-0.1.1.jar:na]
        at de.slux.line.friday.FridayBotApplication.handleTextMessageEvent(FridayBotApplication.java:231) [friday-bot-0.1.1.jar:na]
        at sun.reflect.GeneratedMethodAccessor37.invoke(Unknown Source) ~[na:na]

```

**Comment by slux83** [comment]
Fixed for 0.1.1-p4
